### PR TITLE
Message verification

### PR DESCRIPTION
**Pull request by ogajduse**
Wohooo, completed

### CODE REVIEW

**Review by sarkaaa — APPROVED** [review]
Excelent <3 !

**Comment by rligocki** [comment]
I trust you Ondřej. If there will be any bug. You will be fixing them.

**Review by RolandDavidik — APPROVED** [review]
Verim ti :+1: 
Ale Šárka ne :-1:

**Comment by ogajduse** [comment]
Thanks, merging this!

**Pull request merged**
